### ISSUE TITLE
Package manager doesn't work

### ISSUE THREAD

**Issue by dancek** [jsoftware/jandroid#1]
When I click Tools-Package Manager, the following error message is printed:

```
|file name error
|   ((p2+{.p1)}.pp)    1!:2<p
```
This is on jandroid 1.0.15/25, Oneplus 5, Android 7.1.1.

**Comment by cdburke** [comment]
This is a permissions issue. Please see the thread starting http://www.jsoftware.com/pipermail/programming/2017-June/047711.html , and also the android docs at 
http://code.jsoftware.com/wiki/Guides/JAndroid

**Comment by dancek** [comment]
Thanks for the reply! You're right. I didn't understand the significance of sdcard permissions on the wiki page.

I wonder if this could be made more user-friendly though.
