### ISSUE TITLE
I pressed "x:" but "u:" was output.

### ISSUE THREAD

**Issue by Raclamusi** [jsoftware/jandroid#2]
When I press "x:" on the *JKeyboard*, "u:" is output.
https://github.com/jsoftware/jandroid/blob/8b5f00e9bff7dc39be22f3684a2c9586fa142ffd/res/xml/jsym2.xml#L56
Isn't `-1130` an error of `-1131`?

**Comment by bilam** [comment]
Thank you for the report. Fix in the next release.
