### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by AshyIsMe** [jsoftware/jandroid#3]
The dev environment and build steps documentation is quite sparse here.

Could someone please add some documentation on how to get set up in Android Studio (or eclipse?) with this project?

I ran through the "Import project" wizard in Android Studio and eventually got it to build and run in the emulator but J immediately crashes on start in the emulator and AS also has quite a few warnings and recommendations about outdated frameworks and target versions.

Am I correct in assuming that the current dev environment is Eclipse based?
Is there any appetite for moving to Android Studio now that it seems to be the standard for Android dev?
Also is there any appetite for updating the target framework with a view to listing this on the Play store?

I've noticed a few bugs and usability issues that I'd be interested in trying to fix but in general it might encourage more people to help out if onboarding was a bit smoother.

J on Android is by far the best programming environment on a phone that I've come across, even compared to termux offering an almost full unix environment with vim and emacs etc.
I think there's huge potential for J and the other APL family languages on mobile and would love to see some more interface and usability experimentation.

**Comment by bilam** [comment]
J android is not built with eclipse or any ide, instead it uses the command line tool ant. To build it, type 
$ ant release
and then sign the apk, I use jarsigner to do it

ant had been decommissioned by google android toolchain for quite a long time already. It needs some hacking in order to build with ant now.

J android is intended to be able to run on old devices, so that deprecated api are still used. All warnings are ignored.

Project files for android studio or eclipse, etc are welcome. Sorry I use command line tools and being ignorant of IDE.

**Comment by AshyIsMe** [comment]
Ah thanks for explaining that.
I'll give that a try and see how I go.

**Comment by bilam** [comment]
migrated to gradle build system

**Comment by sohang3112** [comment]
> J android is not built with eclipse or any ide, instead it uses the command line tool ant. To build it, type $ ant release and then sign the apk, I use jarsigner to do it
> 
> ant had been decommissioned by google android toolchain for quite a long time already. It needs some hacking in order to build with ant now.
> 
> J android is intended to be able to run on old devices, so that deprecated api are still used. All warnings are ignored.
> 
> Project files for android studio or eclipse, etc are welcome. Sorry I use command line tools and being ignorant of IDE.

@bilam Please add this info to docs (README.md or CONTRIBUTING.md).

**Comment by sohang3112** [comment]
@bilam Opened issue to document these code build instructions: https://github.com/jsoftware/jandroid/issues/6
